package com.android.fitz.fastreading.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.android.fitz.fastreading.db.entity.Test;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST".
*/
public class TestDao extends AbstractDao<Test, String> {

    public static final String TABLENAME = "TEST";

    /**
     * Properties of entity Test.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Photo = new Property(0, String.class, "photo", false, "PHOTO");
        public final static Property Speed = new Property(1, String.class, "speed", false, "SPEED");
        public final static Property Words = new Property(2, String.class, "words", false, "WORDS");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Id = new Property(5, String.class, "id", true, "ID");
    }


    public TestDao(DaoConfig config) {
        super(config);
    }
    
    public TestDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST\" (" + //
                "\"PHOTO\" TEXT," + // 0: photo
                "\"SPEED\" TEXT," + // 1: speed
                "\"WORDS\" TEXT," + // 2: words
                "\"TITLE\" TEXT," + // 3: title
                "\"CONTENT\" TEXT," + // 4: content
                "\"ID\" TEXT PRIMARY KEY NOT NULL );"); // 5: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Test entity) {
        stmt.clearBindings();
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(1, photo);
        }
 
        String speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindString(2, speed);
        }
 
        String words = entity.getWords();
        if (words != null) {
            stmt.bindString(3, words);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(6, id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Test entity) {
        stmt.clearBindings();
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(1, photo);
        }
 
        String speed = entity.getSpeed();
        if (speed != null) {
            stmt.bindString(2, speed);
        }
 
        String words = entity.getWords();
        if (words != null) {
            stmt.bindString(3, words);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(5, content);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(6, id);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5);
    }    

    @Override
    public Test readEntity(Cursor cursor, int offset) {
        Test entity = new Test( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // photo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // speed
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // words
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Test entity, int offset) {
        entity.setPhoto(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSpeed(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWords(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(Test entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Test entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Test entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
